# Generated by Django 2.1.4 on 2019-01-06 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20181223_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='magzin',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
